language: php

php:
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

services:
  - mysql

before_script:
  - cp .env.example .env
  - php artisan key:generate
  - mysql -e 'create database if not exists parserbin;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  
script:
  - vendor/bin/phpunit
