language: php

php:
  - 7.1
  - 7.2
  - latest

before_script:
  - cp .env.travis .env
  - mysql -e 'create database parserbin;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
